config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'new_reviews', to: 'courses#create_reviews'
  resources :courses
  resources :reviews
  resources :difficulties
  resources :institutions
  resources :majors



  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  # handling login, logout
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/institution.rb
class Institution < ApplicationRecord
  # RELATIONSHIPS
  has_many :majors, dependent: :destroy
  has_many :courses, through: :majors
  has_many :reviews, through: :courses
  has_one_attached :logo

  accepts_nested_attributes_for :majors,
                                 allow_destroy: true
                            
  # VALIDATIONS
  validates :name, 
    presence: true, 
    uniqueness: { case_sensitive: false }, 
    length: {minimum: 2, maximum: 100}
  
  validates :city, 
    presence: true, 
    length: {minimum: 2, maximum: 100} 
  
  validates :country, 
    presence: true, 
    length: {minimum: 2, maximum: 25}  

  validate :state_is_real

  def state_is_real

    legit_states = []
    country_keys = CS.countries.keys
    country_keys.each do |country|
      states = CS.states(country).values
      legit_states.push(*states)
    end  

    us_states = ['AL', 'AK', 'AS', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FM', 'FL', 'GA', 'GU', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MH', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'MP', 'OH', 'OK', 'OR', 'PW', 'PA', 'PR', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VI', 'VA', 'WA', 'WV', 'WI', 'WY', 'AE', 'AA', 'AP']
    canada_provinces = ['AB', 'BC', 'MB', 'NB', 'NL', 'NS', 'ON', 'PE', 'QC', 'SK']
    legit_states.push(*us_states)
    legit_states.push(*canada_provinces)

    if !legit_states.include?(self.state) 
      errors.add(:state, "is not a valid state/province. Check spelling and/or capitalization.")
    end
  end


  # FORMATTING
  before_save { self.name = self.name.downcase.titleize }
  before_save { self.city = self.city.downcase.titleize }
  before_validation :statify


  def statify
    if self.state.present?

      if self.country == "USA"
        self.state = self.state.upcase
        case self.state
        when "ALABAMA"
          self.state = "AL"
        when "ALASKA"
          self.state = "AK"
        when "ARIZONA"
          self.state = "AZ"
        when "ARKANSAS"
          self.state = "AR"
        when "CALIFORNIA"
          self.state = "CA"
        when "COLORADO"
          self.state = "CO"
        when "CONNECTICUT"
          self.state = "CT"
        when "DISTRICT OF COLUMBIA"
          self.state = "DC"
        when "DELAWARE"
          self.state = "DE"
        when "FLORIDA"
          self.state = "FL"
        when "GEORGIA"
          self.state = "GA"
        when "HAWAII"
          self.state = "HI"
        when "IDAHO"
          self.state = "ID"
        when "ILLINOIS"
          self.state = "IL"
        when "INDIANA"
          self.state = "IN"
        when "IOWA"
          self.state = "IA"
        when "KANSAS"
          self.state = "KS"
        when "KENTUCKY"
          self.state = "KY"
        when "LOUISIANA"
          self.state = "LA"
        when "MAINE"
          self.state = "ME"
        when "MARYLAND"
          self.state = "MD"
        when "MASSACHUSETTS"
          self.state = "MA"
        when "MICHIGAN"
          self.state = "MI"
        when "MINNESOTA"
          self.state = "MN"
        when "MISSISSIPPI"
          self.state = "MS"
        when "MISSOURI"
          self.state = "MO"
        when "MONTANA"
          self.state = "MT"
        when "NEBRASKA"
          self.state = "NE"
        when "NEVADA"
          self.state = "NV"
        when "NEW HAMPSHIRE"
          self.state = "NH"
        when "NEW JERSEY"
          self.state = "NJ"
        when "NEW MEXICO"
          self.state = "NM"
        when "NEW YORK"
          self.state = "NY"
        when "NORTH CAROLINA"
          self.state = "NC"
        when "NORTH DAKOTA"
          self.state = "ND"
        when "OHIO"
          self.state = "OH"
        when "OKLAHOMA"
          self.state = "OK"
        when "OREGON"
          self.state = "OR"
        when "PENNSYLVANIA"
          self.state = "PA"
        when "RHODE ISLAND"
          self.state = "RI"
        when "SOUTH CAROLINA"
          self.state = "SC"
        when "SOUTH DAKOTA"
          self.state = "SD"
        when "TENNESSEE"
          self.state = "TN"
        when "TEXAS"
          self.state = "TX"
        when "UTAH"
          self.state = "UT"
        when "VERMONT"
          self.state = "VT"
        when "VIRGINIA"
          self.state = "VA"
        when "WASHINGTON"
          self.state = "WA"
        when "WEST VIRGINIA"
          self.state = "WV"
        when "WISCONSIN"
          self.state = "WI"
        when "WYOMING"
          self.state = "WY"
        end

      elsif self.country == "Canada"
        self.state = self.state.upcase
        case self.state
        when "ALBERTA"
          self.state = "AB"
        when "BRITISH COLUMBIA"
          self.state = "BC"
        when "MANITOBA"
          self.state = "MB"
        when "NEW BRUNSWICK"
          self.state = "NB"
        when "NEWFOUNDLAND AND LABRADOR"
          self.state = "NL"
        when "NOVA SCOTIA"
          self.state = "NS"
        when "ONTARIO"
          self.state = "ON"
        when "PRINCE EDWARD ISLAND"
          self.state = "PE"
        when "QUEBEC"
          self.state = "QC"
        when "SASKATCHEWAN"
          self.state = "SK"
        end
      end
    end
  end

end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
    before_action :set_institution, only: [:show, :destroy, :update, :edit]

    def index
        @institutions = Institution.order(id: "ASC")
    end
    
    def new
        @institution = Institution.new

        #generate updated countries list
        @countries_for_select = CS.countries.values.sort
        #remove 2 false values at end of array
        @countries_for_select.pop()
        @countries_for_select.pop()
        #put USA at top of list
        @countries_for_select.unshift("USA")
        @countries_for_select.delete("United States")
    end

    def create
        @institution = Institution.new(institution_params)
        @institution.save
        if @institution.save
            flash[:success] = "New institution has been created"
            redirect_to institution_path(@institution)
        else 
            #generate updated countries list
            @countries_for_select = CS.countries.values.sort
            #remove 2 false values at end of array
            @countries_for_select.pop()
            @countries_for_select.pop()
            #put USA at top of list
            @countries_for_select.unshift("USA")
            @countries_for_select.delete("United States")
            render 'new'
        end
    end

    def show
       @instituion = Institution.find(params[:id])

       #Generate list of courses for this instituion
       #@courses = Course.where("institution_id = ?", params[:institution_id]) 
    end

    def destroy
        @institution = Institution.find(params[:id])
        @institution.destroy
        
        flash[:danger] = "institution was deleted"
        redirect_to root_path
    end

    def edit
        @instituion = Institution.find(params[:id])
    end

    def update
        @institution = Institution.find(params[:id])
        if @institution.update(institution_params)
            flash[:success] = "institution information was updated"
            redirect_to institution_path(@institution)
        else
            render 'edit'
        end
    end

    private
    def set_institution
        @institution = Institution.find(params[:id])
    end

    def institution_params
        params.require(:institution).permit(
            :name, 
            :city,
            :state,
            :country,
            :logo,
            majors_attributes: [:majorname, :description, :institution_id]
        )
    end 
end

app/views/institutions/_form.html.erb
<%= render 'shared/errors', obj: @institution %>

<div class = "row">
    <div class = "col-xs-12">
        <%= form_with( model: @institution, local: true, class: "form-horizontal") do |f| %>
        
        
            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label :name %>
                </div>

                <div class = "col-sm-8">
                    <%= f.text_field :name, class: "form-control", placeholder: "Name of Institution (Required)", autofocus: true %>
                </div>
            </div>

            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label :city %>
                </div>

                <div class = "col-sm-8">
                    <%= f.text_field :city, class: "form-control", placeholder: "City Name (Required)", autofocus: true %>
                </div>
            </div>

            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label "State/Province" %>
                </div>

                <div class = "col-sm-8">
                    <%= f.text_field :state, class: "form-control", placeholder: "State/Province Name (if applicable)", autofocus: true %>
                </div>
            </div>

            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label :country %>
                </div>

                <div class = "col-sm-8">
                    <%= f.select :country, options_for_select(@countries_for_select), class: "form-control", prompt: "Select a Country", autofocus: true %>
                </div>
            </div>

            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label :logo %>
                </div>

                <div class = "col-sm-8">
                    <%= f.file_field :logo, class: "form-control"%>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
        

            
        <% end %>
    </div>
</div>

app/views/institutions/edit.html.erb
<h3 align="center" class="page-title">Edit Information for <%= @instituion.name %></h3>

<div align="center">
  <% if @institution.logo.attached? %>
    <img src="<%= (url_for(@institution.logo)) %>" alt="<%= @institution.name %> logo" width="700" height="300">
  <% end %>
</div>

<%= render 'form' %>

<%= link_to "Back to #{@institution.name} Homepage", institution_path(@institution) %>

app/views/institutions/index.html.erb
<h1>Listing all Institutions</h1>
<p><%= link_to "Submit a new Institution", new_institution_path %></p>

<% @institutions.each do |institution| %>
    <div class = "row">
        <div class = "col-xs-8">
            <div class = "well well-lg">
                <div class = "institution-name-and-location">
                    <% if institution.state? %>
                        <%= link_to institution.name, institution_path(institution) %></td>
                        - 
                        <%= institution.city %>, <%= institution.state %>, <%= institution.country %>
                    <% else %>
                        <%= link_to institution.name, institution_path(institution) %></td>
                        - 
                        <%= institution.city %>, <%= institution.country %>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/institutions/new.html.erb
<h3 align="center" class="page-title">Submit a New Institution</h3>

<%= render 'form' %>

<%= link_to 'Back to Homepage', root_path %>

app/views/institutions/show.html.erb
<div align="center">
  <% if @institution.logo.attached? %>
    <img src="<%= (url_for(@institution.logo)) %>" alt="<%= @institution.name %> logo" width="700" height="300">
  <% end %>
</div>

<div class = "well well-lg">
  <h1 align="center"><%= @instituion.name %></h1>
  <% if @institution.state? %>
    <h3 align="center"><%= @institution.city %>, <%= @institution.state %>, <%= @institution.country %></h2>
  <% else %>
    <h3 align="center"><%= @institution.city %>, <%= @institution.country %></h2>
  <% end %>
</div>

<!-- DISABLE AUTHENTICATION FOR LOCAL DEVELOPMENT -->

<%
=begin %>
<!--
<div class = "institution-actions">
    <% if logged_in? %> 
        <% if current_user.admin? %>
            <%= link_to 'Edit Institution', edit_institution_path(@institution), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete Institution', institution_path(@institution), method: :delete, data: {confirm: "Are you sure you want to delete the institution?"}, class: "btn btn-xs btn-danger" %>
        <% end %> 
    <% end %>  
</div>
-->
<%
=end %>


<!-- NO AUTHENTICATION FOR LOCAL DEVELOPMENT -->


<div class = "institution-actions">  
  <div align="center"> 
    <%= link_to 'Edit Institution', edit_institution_path(@institution), class: "btn btn-xs btn-primary" %>
    <%= link_to 'Delete Institution', institution_path(@institution), method: :delete, data: {confirm: "Are you sure you want to delete the institution?"}, class: "btn btn-xs btn-danger" %>
    <%= link_to 'Add Major', new_major_path(institution_id: @institution.id), class: "btn btn-xs btn-success" %>
  </div>
</div>


<div class = "well well-lg">
  <h2 align="center">Major Fields of Study</h2>

  <% @institution.majors.each do |m| %>
    <div>
      <%= link_to "#{m.majorname}", major_path(m) %>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Course List<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% m.courses.each do |c| %>
                <li><%= link_to "#{c.coursename}", course_path(c) %></li>
              <% end %>   
            </ul>
          </li>
        </ul>
      </div>

    </div>
  <% end %>

</div>