config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'new_reviews', to: 'courses#create_reviews'
  resources :courses
  resources :reviews
  resources :difficulties
  resources :institutions
  resources :majors



  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  # handling login, logout
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/major.rb
class Major < ApplicationRecord
  
  # RELATIONSHIPS
  belongs_to :institution
  has_many :courses, dependent: :destroy
  has_many :reviews, through: :courses
  accepts_nested_attributes_for :courses,
                                   allow_destroy: true

  # VALIDATIONS
  validates :majorname, 
    presence: true, 
    uniqueness: { case_sensitive: false, scope: :institution_id, message: "already exists for this institution" },
    length: {minimum: 2, maximum: 100}

  # FORMATTING
  before_save { self.majorname = self.majorname.downcase.titleize }

end

app/controllers/majors_controller.rb
class MajorsController < ApplicationController
  before_action :set_major, only: [:show, :edit, :update, :destroy]

  # GET /majors
  def index
    @majors = Major.all
  end

  # GET /majors/1
  def show
    @institution = Institution.find(@major.institution_id)
  end

  # GET /majors/new
  def new
    @institution = Institution.find(params[:institution_id])
    @major = @institution.majors.new
  end

  # GET /majors/1/edit
  def edit
    @institution = Institution.find(@major.institution_id)
  end

  # POST /majors
  def create
    @major = Major.new(major_params)
    @institution = Institution.find(@major.institution_id)

    @major.save
    if @major.save
      flash[:success] = "New major has been created"
      redirect_to major_path(@major)
    else 
      render 'new'
    end
  end

  # PATCH/PUT /majors/1
  def update
    respond_to do |format|
      if @major.update(major_params)
        format.html { redirect_to @major, notice: 'Major was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /majors/1
  def destroy
    @institution = Institution.find(@major.institution_id)
    @major.destroy
    
    flash[:success] = 'Major was successfully destroyed.'
    redirect_to institution_path(@institution)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_major
      @major = Major.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def major_params
      params.require(:major).permit(
        :majorname, 
        :description, 
        :institution_id,
        courses_attributes: [:coursename, :course_content, :prerequisite, :proctoredexams, :groupwork, :textbook]
      )
    end
end

app/views/majors/_form.html.erb
<%= render 'shared/errors', obj: @major %>

<div align="center">
    <% if @institution.logo.attached? %>
        <img src="<%= (url_for(@institution.logo)) %>" alt="<%= @institution.name %> logo" width="700" height="300">
    <% else %>
        <h1><%= @institution.name %></h1>
    <% end %>
</div>

<div class = "row">
    <div class = "col-xs-12">
        <%= form_with( model: @major, local: true, class: "form-horizontal") do |f| %>
        
            <%= f.hidden_field :institution_id, :value => @institution.id %>

            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label "Name" %>
                </div>

                <div class = "col-sm-8">
                    <%= f.text_field :majorname, class: "form-control", placeholder: "Name of Major (Required)", autofocus: true %>
                </div>
            </div>

            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label :description %>
                </div>

                <div class = "col-sm-8">
                    <%= f.text_field :description, class: "form-control", placeholder: "Description of Major", autofocus: true %>
                </div>
            </div>

           
            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
            
        <% end %>
    </div>
</div>

app/views/majors/edit.html.erb
<h3 align="center" class="page-title">Edit Information for <%= @major.majorname %> Major</h3>

<%= render 'form', major: @major %>

<%= link_to "Back to #{@major.majorname} Homepage", major_path(@major) %>

app/views/majors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Majors</h1>

<table>
  <thead>
    <tr>
      <th>Majorname</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @majors.each do |major| %>
      <tr>
        <td><%= major.majorname %></td>
        <td><%= major.description %></td>
        <td><%= link_to 'Show', major %></td>
        <td><%= link_to 'Edit', edit_major_path(major) %></td>
        <td><%= link_to 'Destroy', major, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Major', new_major_path %>

app/views/majors/new.html.erb
<h1 align="center" class="page-title">Submit a New Major</h3>

<%= render 'form', major: @major %>

<%= link_to "Back to #{@institution.name} Homepage", institution_path(@institution) %>

app/views/majors/show.html.erb
<div align="center">
    <% if @institution.logo.attached? %>
        <img src="<%= (url_for(@institution.logo)) %>" alt="<%= @institution.name %> logo" width="700" height="300">
    <% else %>
        <h1 align="center"><%= @institution.name %></h1>
        <% if @institution.state? %>
            <h3 align="center"><%= @institution.city %>, <%= @institution.state %>, <%= @institution.country %></h2>
        <% else %>
            <h3 align="center"><%= @institution.city %>, <%= @institution.country %></h2>
        <% end %>
    <% end %>
</div>

<h2 align="center">Major: <%= @major.majorname %></h2>

<div class = "well well-lg">
    <h4 class = "center description"><strong style="color:blue;">Major Description:</strong></h4>
    <p align="center"><%= @major.description %></p>

    <div class = "major-actions">  
      <div align="center">      
        <%= link_to 'Edit major', edit_major_path(@major), class: "btn btn-xs btn-primary" %>
        <%= link_to 'Delete major', major_path(@major), method: :delete, data: {confirm: "Are you sure you want to delete the major?"}, class: "btn btn-xs btn-danger" %>  
        <%= link_to 'Add Course', new_course_path(institution_id: @institution.id, major_id: @major.id), class: "btn btn-xs btn-success" %> 
        <%= link_to "Back to #{@institution.name} Homepage", institution_path(@institution), class: "btn btn-xs btn-danger" %>
      </div>
    </div>

</div>



<!-- DISABLE AUTHENTICATION FOR LOCAL DEVELOPMENT -->

<% 
=begin %>
<!--
<div class = "major-actions">  
    <% if logged_in? %> 
        <% if current_user.admin? %>
            <%= link_to 'Edit major', edit_major_path(@major), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete major', major_path(@major), method: :delete, data: {confirm: "Are you sure you want to delete the major?"}, class: "btn btn-xs btn-danger" %>
        <% end %> 
    <% end %> 
</div>
-->
<% 
=end %>


<!-- ENABLE FUNCTIONALITY FOR LOCAL DEVELOPMENT --->
  
<br />

<div class = "well well-lg">
  <h2 align="center"><%= @major.majorname %> Courses</h2>
  <% @major.courses.each do |c| %>
    <div align="center">
      <p><%= link_to "#{c.coursename}", course_path(c) %> 
        &nbsp;&nbsp;.........&nbsp;&nbsp; 
        <%= c.reviews.count %> reviews</p>
      <br />
    </div>
  <% end %>
</div>