config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'new_reviews', to: 'courses#create_reviews'
  resources :courses
  resources :reviews
  resources :difficulties
  resources :institutions
  resources :majors



  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  # handling login, logout
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    before_action :set_course, only: [:show, :destroy, :update, :edit]

    def index
        @courses = Course.order(id: "ASC")
    end
    
    def new
        @institution = Institution.find(params[:institution_id])
        @major = Major.find(params[:major_id])

        # must assign the course with a belong_to relationship with major
        @course = @major.courses.new
        @course.institution_id = params[:institution_id]
    end

    def create
        @course = Course.new(course_params)
        @institution = Institution.find(@course.institution_id)
        @major = Major.find(@course.major_id)

        @course.save
        if @course.save
            flash[:success] = "New course has been created"
            redirect_to course_path(@course)
        else 
            render 'new'
        end
    end

    def show
        @institution = Institution.find(@course.institution_id)
        @major = Major.find(@course.major_id)

        # Retrieving difficuly score from nested attributes
        @score1 = @course.reviews.where(difficulty: 1).count
        @score2 = @course.reviews.where(difficulty: 2).count
        @score3 = @course.reviews.where(difficulty: 3).count
        @score4 = @course.reviews.where(difficulty: 4).count
        @score5 = @course.reviews.where(difficulty: 5).count
        @challenge_score = {"1 - Very Easy" => @score1, "2 - Somewhat Easy" => @score2, "3 - Average" => @score3, "4 - Challenging" => @score4, "5 - Very Difficult" => @score5}

        @career1 = @course.reviews.where(benefit: "1").count
        @career2 = @course.reviews.where(benefit: "2").count
        @career3 = @course.reviews.where(benefit: "3").count
        @career4 = @course.reviews.where(benefit: "4").count
        @career5 = @course.reviews.where(benefit: "5").count
        @career_benefit = {"1 - Not Beneficial" => @career1, "2 - Hardly Beneficial" => @career2, "3 - Somewhat Beneficial" => @career3, "4 - Beneficial" => @career4, "5 - Very Beneficial" => @career5}

        @time1 = @course.reviews.where(time_spent: "1-3").count
        @time2 = @course.reviews.where(time_spent: "4-6").count
        @time3 = @course.reviews.where(time_spent: "7-9").count
        @time4 = @course.reviews.where(time_spent: "10-12").count
        @time5 = @course.reviews.where(time_spent: "13-15").count
        @time_spent = {"1-3 hours" => @time1, "4-6 hours" => @time2, "7-9 hours" => @time3, "10-12 hours" => @time4, "13-15 hours" => @time5}
    end

    def destroy
        @course = Course.find(params[:id])
        @major = Major.find(@course.major_id)
        @course.destroy
        
        flash[:danger] = "Course was deleted"
        redirect_to major_path(@major)
    end

    def edit
        @institution = Institution.find(@course.institution_id)
        @major = Major.find(@course.major_id)
    end

    def update
        @course = Course.find(params[:id])
        if @course.update(course_params)
            flash[:success] = "Course was Updated"
            redirect_to course_path(@course)
        else
            render 'edit'
        end
    end

    private
    
    def set_course
        @course = Course.find(params[:id])
    end

    def course_params
        params.require(:course).permit(
            :coursename, 
            :course_content, 
            :prerequisite, 
            :proctoredexams, 
            :groupwork, 
            :textbook,
            :institution_id, 
            :major_id,
            reviews_attributes: [:reviews_content, :difficulty, :benefit, :time_spent],
        )
    end 
end

app/views/courses/_form.html.erb
<%= render 'shared/errors', obj: @course %>

<div align="center">
    <% if @institution.logo.attached? %>
        <img src="<%= (url_for(@institution.logo)) %>" alt="<%= @institution.name %> logo" width="700" height="300">
    <% else %>
        <h1><%= @institution.name %></h1>
    <% end %>
</div>

<div class = "row">
    <div class = "col-xs-12">
        <%= form_with( model: @course, local: true, class: "form-horizontal") do |f| %>
        
            <%= f.hidden_field :institution_id, :value => @institution.id %>
            <%= f.hidden_field :major_id, :value => @major.id %>

            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label "Name" %>
                </div>

                <div class="col-sm-8">
                    <%= f.text_field :coursename, class: "form-control", placeholder: "Name of Course (Required)", autofocus: true %>
                </div>
            </div>


            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label "Course Content" %>
                </div>

                <div class="col-sm-8">
                    <%= f.text_field :course_content, class: "form-control", placeholder: "Description of Course (Required)", autofocus: true %>
                </div>
            </div>

            <div class = "form-group">
                <div class = "control-label col-sm-2">
                    <%= f.label :course_content %>
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label "Prerequisite(s)" %>
                </div>

                <div class="col-sm-8">
                    <%= f.text_field :prerequisite, class: "form-control", placeholder: "Prerequisite(s) of class", autofocus: true %>
                    <%= f.label :prerequisite %>
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label "Proctored Exams" %>
                </div>

                <div class="col-sm-8">
                    <%= f.radio_button :proctoredexams, "Yes" %>
                    <%= f.label :proctoredexams, "Yes" %>
                    <%= f.radio_button :proctoredexams, "No" %>
                    <%= f.label :proctoredexams, "No" %>
                </div>

                <div class="col-sm-8">
                    <%= f.text_field :proctoredexams, class: "form-control", placeholder: "Proctored Exams of class", autofocus: true %>
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label "Group Work Required" %>
                </div>

                <div class="col-sm-8">
                    <%= f.text_field :groupwork, class: "form-control", placeholder: "Group Work of class", autofocus: true %>
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-sm-2">
                    <%= f.label :textbook %>
                </div>

                <div class="col-sm-8">
                    <%= f.text_field :textbook, class: "form-control", placeholder: "Textbook of class", autofocus: true %>
                </div>
            </div>
     
            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-10">
                    <%= f.submit class: "btn btn-primary btn-lg" %>
                </div>
            </div>
            
        <% end %>
    </div>
</div>

app/views/courses/edit.html.erb
<%
=begin %>
<% if current_user.admin? %>
<% end %>
=end %>

<h3 align="center" class="page-title">Edit Course: <%= @course.coursename %></h1>

<%= render 'form' %>

<%= link_to "Back to Course Page", course_path(@course) %>

app/views/courses/index.html.erb
<% @courses.each do |course| %>
    <div class="row">
        <div class="col-xs-8" col-xs-offset-2">
            <div class="well well-lg">
                <div class="course-title">
                    <%= link_to course.coursename, course_path(course) %></td>
                    <span class="rating">
                        <nobr>
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
                            <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                            <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
                        </nobr>
                    </span>
                </div>
                <div class="course-body">
                    <%= truncate(course.course_content, length: 100) %></td>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/courses/new.html.erb
<h3 align="center" class="page-title">Create a Course</h3>

<%= render 'form' %>

<%= link_to "Back to #{@major.majorname} Homepage", major_path(@major) %>

app/views/courses/show.html.erb
<div align="center">
    <% if @institution.logo.attached? %>
        <img src="<%= (url_for(@institution.logo)) %>" alt="<%= @institution.name %> logo" width="700" height="300">
    <% else %>
        <h1 align="center"><%= @institution.name %></h1>
        <% if @institution.state? %>
            <h3 align="center"><%= @institution.city %>, <%= @institution.state %>, <%= @institution.country %></h2>
        <% else %>
            <h3 align="center"><%= @institution.city %>, <%= @institution.country %></h2>
        <% end %>
    <% end %>
</div>


<h2 align="center">Course Title: <%= @course.coursename %></h2>

<div class="well col-xs-8 col-xs-offset-2">
    <h4 class="center description"><strong style="color:blue;">Course Detail:</strong></h4>
    <hr>
    <%= simple_format(@course.course_content) %>
    <li>Pre-requisite courses: <%= @course.prerequisite %></li>
    <li>Proctored Exams: <%= @course.proctoredexams %></li>
    <li>Group Work: <%= @course.groupwork %></li>
    <li>Textbook: <%= @course.textbook %></li>

    <div class="course-actions">

<!-- DISABLE AUTHENTICATION FOR LOCAL DEVELOPMENT -->

<% 
=begin %>
    <!--
   
    <% if logged_in? %> 
        <% if current_user.admin? %>
            <%= link_to 'Edit Course', edit_course_path(@course), class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete Course', course_path(@course), method: :delete, data: {confirm: "Are you sure you want to delete the course?"}, class: "btn btn-xs btn-danger" %>
        <% else %>
            <%= link_to 'Create Reviews', new_review_path, class: "btn btn-xs btn-success" %>
        <% end %> 
    <% end %> 
    
    -->
<% 
=end %>


<!-- ENABLE FUNCTIONALITY FOR LOCAL DEVELOPMENT --->
  
        
        <%= link_to 'Edit Course', edit_course_path(@course), class: "btn btn-xs btn-primary" %>
        <%= link_to 'Delete Course', course_path(@course), method: :delete, data: {confirm: "Are you sure you want to delete the course?"}, class: "btn btn-xs btn-danger" %>
        <%= link_to 'Create a Review', new_review_path(course_id: @course.id, institution_id: @institution.id, major_id: @major.id), class: "btn btn-xs btn-success" %>
        <%= link_to "Back to #{@major.majorname} Homepage", major_path(@major), class: "btn btn-xs btn-primary" %>
        <%= link_to "Back to #{@institution.name} Homepage", institution_path(@institution), class: "btn btn-xs btn-danger" %>

          


    </div>
</div>

<div class="col-md-6">
    <h2>Reviews from other students</h2>
    <% @course.reviews.each do |i| %>
        <ul class="nav nav-tabs nav-stacked col-md-12 col-lg-12 col-sm-12 well ng-scope">
            <li class="ng-binding"><%= i.reviews_content %></li>
            <li class="ng-binding pull-right"><%= i.created_at.strftime('%Y/%m/%d')%></li>
        </ul>
    <% end %>
    </ul>
</div>

<div class="col-md-6">
    <h2 align="center">Challenging Scores</h2>
    <%= pie_chart @challenge_score %>

    <h2 align="center">Time Spent per Week</h2>
    <%= pie_chart @time_spent %>

    <h2 align="center">Career Benefit Score</h2>
    <%= pie_chart @career_benefit %>
</div>