config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'new_reviews', to: 'courses#create_reviews'
  resources :courses
  resources :reviews
  resources :difficulties
  resources :institutions
  resources :majors



  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  # handling login, logout
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_footer.html.erb
<footer class="blog-footer">
    <a href="https://github.com/nao4869"><p><%= @copyright %></p>
</footer>
        

app/views/layouts/_messages.html.erb
<div class="row">
    <div class="col-xs-8 col-xs-offset-2">
        <% flash.each do |name, msg| %>
            <div class='alert alert-<%= "#{name}" %>'>
                <a href="#" class="close" data-dismiss="alert">&#215;</a>
                <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span>
      </button>

      <%= link_to "Course Search", root_path, class: "navbar-brand", id: "logo" %>
      <div class="row">
        <div class="column">
          <img src="/images/osu-logo.svg" width="120px" />
        </div>
      </div>

    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">List of Institutions<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Institution.all.each do |inst| %>
              <li><%= link_to "#{inst.name}", institution_path(inst) %></li>
            <% end %>   
          </ul>
        </li>
  
        
          <li><%= link_to "Create New Institution", new_institution_path %></li>
   
      </ul>
       
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            User Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit user profile", edit_user_path(current_user) %></li>
              <li><%= link_to "View user profile", user_path(current_user) %></li>              
            </ul>
          </li>
        
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
          <li><%= link_to 'Signup', signup_path %></li>
        <% end %>
      </ul>

  </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>OSU Course Search</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>